### ISSUE TITLE
Akhil Singamneni CSP Individual Final 

### ISSUE THREAD

**Issue by Akhil353** [Akhil353/student#3]
[Individual Blog Review](https://akhil353.github.io/student//2024/02/20/CPT-review.html)

[CPT Video](https://drive.google.com/file/d/1kFGzLO6gLRhiHDb6hm57EX7dUyWYtk6t/view?usp=sharing)

Additions made from review:
- Specified which code is sequencing, selecting, and iterating
- Added images of the code to the 1st and 2nd box to show what they are referencing

**Comment by RonitT1234** [comment]
Hey Akhil your individual blog looks good. I think the table format was a good choice to organize the information. I would sugest to add code for the first two boxes but I'm not sure if that's neccassary.  I would also suggest to specifcally label the sequencing, selection, and iteration in your post similar to how you did for the procedure. Your video is really well made but as a minor suggestion I would say to keep the text in one spot. 

0.98/1
