### ISSUE TITLE
Debugging Event

### ISSUE THREAD

**Issue by Akhil353** [Akhil353/student#4]
#### 1. Start Backend using Debugging
<img width="960" alt="Screenshot 2024-03-07 at 3 26 43 PM" src="https://github.com/Akhil353/student/assets/106125268/3c3a543f-b9ab-41ef-88d2-a9b30cbfa91a">

#### 2. Set break point at the beginning of endpoint code 
<img width="576" alt="Screenshot 2024-03-07 at 3 31 17 PM" src="https://github.com/Akhil353/student/assets/106125268/dfc87ab8-415f-41b4-bea1-29df961501ca">

#### 3. Start in frontend with split screen loading source for an API fetch using GET.
<img width="1464" alt="Screenshot 2024-03-08 at 3 42 25 PM" src="https://github.com/Akhil353/student/assets/106125268/adf9eae7-01ed-461d-b56c-d9b253d1f79d">

#### 4/5. Set break point on fetch, inside .then, inside .fetch + Run frontend, screen capture break at fetch while 
<img width="1410" alt="Screenshot 2024-03-08 at 3 40 37 PM" src="https://github.com/Akhil353/student/assets/106125268/f14f1d79-57e9-47ae-bc7a-889bf41e620c">

#### 6. Press play on frontend and observe backend
<img width="1045" alt="Screenshot 2024-03-08 at 3 43 46 PM" src="https://github.com/Akhil353/student/assets/106125268/084c8f76-d4e2-4c12-a60b-ca180be33fb6">

#### 7. Press step over on backend until you have obtained data from database, screen capture Python Object
<img width="671" alt="Screenshot 2024-03-07 at 4 17 14 PM" src="https://github.com/Akhil353/student/assets/106125268/5011ebff-65b1-4d16-81f8-6b98503c2d43">

#### 10. Step in until you see data, screen capture capturing break point and Data (Data is in bottom right).
<img width="1420" alt="Screenshot 2024-03-08 at 3 44 45 PM" src="https://github.com/Akhil353/student/assets/106125268/ca40ac66-c22d-460b-9ff1-e02626d656f7">

**Comment by spooketti** [comment]
1.82 Great work on debugging! Perhaps a bit more writing and that'd be great.

**Comment by advikg** [comment]
1.80/2.00 Great work on debugging, good knowledge on breakpoints. main - points for using basic login function, supposed to use a new POST method or some other method not on the site by default. Also make sure to change usernames for default accounts(toby, hop, etc.)
